# config.py

# ===== TELEGRAM =====
import os

TOKEN = os.getenv("TOKEN")
BINANCE_API_KEY = os.getenv("BINANCE_API_KEY")
BINANCE_API_SECRET = os.getenv("BINANCE_API_SECRET")


ADMIN_IDS = [5297138695]

MAX_FREE_PER_DAY = 2
MAX_VIP_PER_DAY = 10

# ===== BINANCE =====
BINANCE_API_KEY = "H1K6lHJPoNWJVftYX5I7PICQWgSVwUQkrkBvKot4ZlKZkuOKojkMEnxndMWFHdrd"
BINANCE_API_SECRET = "kX65G0UhWKo50Ynz1nARcIgJwC4UJXfhCVJN4qCygG5qPKvl6WyQeLRaoXgQ2qnD"

# ===== TRADING =====
PAIRS = ["BTCUSDT", "ETHUSDT"]
TIMEFRAME = "5m"          # scalping
LEVERAGE = 5
RISK_PER_TRADE = 0.01     # 1%
MAX_TRADES_AT_ONCE = 1

# ===== BACKTEST =====
BACKTEST_MONTHS = 6
